# Generated by Django 4.0.4 on 2022-05-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_login_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='designation',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
