# Generated by Django 4.0.4 on 2022-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_candidates_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('contact_no', models.CharField(default='', max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
